sudo: required

services:
   - docker

before_install: 
   - docker build -t djcharles26/testful -f Dockerfile.dev .

script:
  - docker run -e CI=true djcahrles26/testful npm run test

language: generic 